// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Active(): $CancellablePromise<boolean> {
    return $Call.ByID(819846437);
}

export function BeginPartyRound(id: string, round: number, rounds: number, deadline: number, mapStyle: string): $CancellablePromise<void> {
    return $Call.ByID(1451094648, id, round, rounds, deadline, mapStyle);
}

export function ClosePartyRound(id: string, round: number): $CancellablePromise<$models.PartyHostPlayer[] | null> {
    return $Call.ByID(951521993, id, round);
}

export function FinishParty(id: string): $CancellablePromise<$models.PartyHostState> {
    return $Call.ByID(752630456, id);
}

export function GetPartyHostState(id: string): $CancellablePromise<$models.PartyHostState> {
    return $Call.ByID(684255826, id);
}

export function LaunchParty(mapID: string, theme: string, accentColor: string): $CancellablePromise<$models.PartyHostState> {
    return $Call.ByID(27297256, mapID, theme, accentColor);
}

export function LockPartyRoster(id: string): $CancellablePromise<$models.PartyHostState> {
    return $Call.ByID(3824418251, id);
}

export function PublishPartyReveal(id: string, reveal: $models.PartyRoundReveal): $CancellablePromise<void> {
    return $Call.ByID(2250165803, id, reveal);
}

export function ResetParty(id: string): $CancellablePromise<void> {
    return $Call.ByID(553110246, id);
}

export function StopParty(id: string): $CancellablePromise<void> {
    return $Call.ByID(1459140293, id);
}
