// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseGame(): $CancellablePromise<void> {
    return $Call.ByID(3879623943);
}

export function ExportMaps(): $CancellablePromise<boolean> {
    return $Call.ByID(3698723838);
}

export function FocusLauncher(): $CancellablePromise<void> {
    return $Call.ByID(2985176669);
}

export function GameReady(mapID: string): $CancellablePromise<void> {
    return $Call.ByID(4188255620, mapID);
}

export function GetGameWindowState(): $CancellablePromise<$models.GameWindowState> {
    return $Call.ByID(1408848652);
}

export function LaunchMap(mapID: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(4127136374, mapID, mode);
}

export function SetGameFullscreen(enabled: boolean): $CancellablePromise<$models.GameWindowState> {
    return $Call.ByID(2531214782, enabled);
}
