// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseGame(): $CancellablePromise<void> {
    return $Call.ByID(2054257745);
}

export function ExportMaps(): $CancellablePromise<boolean> {
    return $Call.ByID(1275126928);
}

export function FocusLauncher(): $CancellablePromise<void> {
    return $Call.ByID(1851256843);
}

export function GameReady(mapID: string): $CancellablePromise<void> {
    return $Call.ByID(589324950, mapID);
}

export function GetGameWindowState(): $CancellablePromise<$models.GameWindowState> {
    return $Call.ByID(2485666454);
}

export function LaunchMap(mapID: string): $CancellablePromise<void> {
    return $Call.ByID(2446668672, mapID);
}

export function SetGameFullscreen(enabled: boolean): $CancellablePromise<$models.GameWindowState> {
    return $Call.ByID(1925625260, enabled);
}
