// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DesktopService from "./desktopservice.js";
import * as PluginService from "./pluginservice.js";
import * as UpdateService from "./updateservice.js";
export {
    DesktopService,
    PluginService,
    UpdateService
};

export type {
    GameWindowState,
    PluginInfo,
    PluginManifest,
    PluginModule,
    PluginPermissions,
    PluginSetting
} from "./models.js";
