// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DesktopService from "./desktopservice.js";
import * as UpdateService from "./updateservice.js";
export {
    DesktopService,
    UpdateService
};

export type {
    GameWindowState
} from "./models.js";
