// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Catalog(): $CancellablePromise<$models.PluginManifest[] | null> {
    return $Call.ByID(799418733);
}

export function EnabledModules(): $CancellablePromise<$models.PluginModule[] | null> {
    return $Call.ByID(443624580);
}

export function Install(id: string): $CancellablePromise<$models.PluginInfo> {
    return $Call.ByID(2825911517, id);
}

export function Installed(): $CancellablePromise<$models.PluginInfo[] | null> {
    return $Call.ByID(3788410916);
}

export function SetEnabled(id: string, enabled: boolean): $CancellablePromise<$models.PluginInfo> {
    return $Call.ByID(1774562395, id, enabled);
}

export function Uninstall(id: string): $CancellablePromise<void> {
    return $Call.ByID(1118432000, id);
}
