// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Catalog(): $CancellablePromise<$models.PluginManifest[] | null> {
    return $Call.ByID(963638277);
}

export function EnabledModules(): $CancellablePromise<$models.PluginModule[] | null> {
    return $Call.ByID(4254696988);
}

export function Install(id: string): $CancellablePromise<$models.PluginInfo> {
    return $Call.ByID(3978639093, id);
}

export function Installed(): $CancellablePromise<$models.PluginInfo[] | null> {
    return $Call.ByID(4049877436);
}

export function SetEnabled(id: string, enabled: boolean): $CancellablePromise<$models.PluginInfo> {
    return $Call.ByID(918422691, id, enabled);
}

export function SetSetting(id: string, key: string, value: string): $CancellablePromise<$models.PluginInfo> {
    return $Call.ByID(1733099010, id, key, value);
}

export function Setting(id: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(1326058186, id, key);
}

export function Uninstall(id: string): $CancellablePromise<void> {
    return $Call.ByID(2944278280, id);
}
